workflows:
  build_ios:
    name: Build iOS without Apple Account
    environment:
      vars:
        NODE_VERSION: 18 # Sử dụng Node.js 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Cài đặt Node.js phiên bản 18
        script: |
          nvm install 18
          nvm use 18
      - name: Cài đặt dependencies
        script: |
          brew install yarn
          yarn install
      - name: Cài đặt Pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app (Simulator only)
        script: |
          xcodebuild -workspace ios/MyApp.xcworkspace \
          -scheme MyApp \
          -sdk iphonesimulator \
          -configuration Release \
          -derivedDataPath build
    artifacts:
      - build/**/*.app
